### ISSUE TITLE
Coil length probably shouldn't be negative

### ISSUE THREAD

**Issue by samreid** [phetsims/masses-and-springs#120]
![image](https://user-images.githubusercontent.com/679486/30253840-54042a04-964a-11e7-8ef6-60ac648e1a90.png)

Discovered in https://github.com/phetsims/axon/issues/137

**Comment by Denz1994** [comment]
Perhaps the naming convention is incorrect for this variable. The coil length undergoes a modelViewTransform that takes its initial model value (positive) and expresses it in the scope of the view bounds. This means that the coil length is more of a distance from the top tip of the spring to the ending tip. I don't think this value is incorrect but instead, the name shouldn't be a "length". It also has no units.

I renamed it to 'coilStretch' and added documentation to make it clear that this is not a length value in the model.

I believe Hook's Law gets positive values because the spring extends from zero -> positive X (in view coordinates). In MAS, we can extend the spring in along the Y axis in both negative and positive orientations, so our stretch may have negative values.
