### ISSUE TITLE
How do we treat energy values that are negative?

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#123]
In [dev 16](http://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.16/masses-and-springs_en.html) we are getting an absolute value for the potential energy so when our mass oscillates pass the bottom of the screen the potential energy gets larger.

Steps to reproduce:
1. Start sim in Energy or Lab Screen
2. Attach a mass and increase the mass to 300g
3. Slightly lower the spring constant and set play speed to slow motion
4. Raise mass to start and oscillation

Notice that when our mass oscillates pass the bottom of the screen the potential energy grows.Currently, we are treating the bottom of the view as a height = 0 meters in the model of our spring system. However, we can oscillate a hanging mass pass the floor making our height < 0 meters.

How should we treat the potential energy at this point? The other energy values are not affected because they are independent of height.

Thoughts @ariel-phet and @arouinfar.

**Comment by arouinfar** [comment]
@ariel-phet the current behavior matches Flash in that the zero point for the gravitational potential energy is just below the masses and abs(GPE) is graphed. The Teacher Tips warn:
> Keep the masses in the window for thorough energy analysis because the PE for the
graph is calculated as an absolute value.

I don't find this to be particularly great UX, but I can understand why Flash behaves the way it does. I think it'd be preferable to provide some constraints so that gravitational potential energy is always positive.

Some possible constraints:
* Move GPE zero point further off-screen
* Limit how far down the mass can be displaced. Currently, the mass can't be dragged further than the navbar, but this distance is variable, depending on the browser's aspect ratio. 
* Limit m, k, and/or g.

Here's one possible configuration to consider for the "worst case". Maximum mass = 200g, Maximum g = Jupiter, Minimum k = 4th tick.

At equilibrium, the mass is still visible on screen.
<img width="1047" alt="screen shot 2017-09-18 at 4 02 33 pm" src="https://user-images.githubusercontent.com/8419308/30566892-200035d0-9c8b-11e7-9538-c572371e9596.png">

If the mass's drag bounds were confined to dev, max displacement would be achieved by fully compressing the spring, rather than stretching.
<img width="1047" alt="screen shot 2017-09-18 at 4 02 58 pm" src="https://user-images.githubusercontent.com/8419308/30566897-221d70c6-9c8b-11e7-89b8-fc12f1e3b76b.png">

The mass would still go pretty far off-screen, but if the zero-point for gravitational potential energy would be moved down about a meter from its current position, the energy would always be positive.
<img width="402" alt="screen shot 2017-09-18 at 4 03 34 pm" src="https://user-images.githubusercontent.com/8419308/30566895-220e0064-9c8b-11e7-882e-49474c4b42d3.png">

Moving the zero-point so far down could result in a very large gravitational potential energy bar, so this might not be ideal.

Probably would be good to have MAS on the design meeting agenda either next week or the week after, so tagging for design.

**Comment by ariel-phet** [comment]
I have a few thoughts, but agreed this needs to be discussed at design meeting. I am fine with moving the zero of GPE off screen, but mainly we need a way to communicate the starting height of the masses to the user. A "variable" GPE zero point might work if we didn't have friction, but I think with friction it would be too confusing.

**Comment by ariel-phet** [comment]
Basically I think it would be by far best if we avoid having negative GPE, as that complicates both the interpretation and the graph.

**Comment by ariel-phet** [comment]
At design meeting we decided to display negative GPE on the bar graph, and remove the stacking behavior from total energy when GPE goes negative. 

@arouinfar do you want to capture any finer grain details here in the issue?

**Comment by arouinfar** [comment]
@Denz1994 @ariel-phet the discussion from yesterday's design meeting has been fleshed out pretty well in the [meeting notes](https://docs.google.com/document/d/13SiJic3Ha_x2FNW_XYFLZGCHRxCG5YLxE_zAu4t5tmQ/edit#heading=h.jaakc7xvrv54), but the main outcomes are:
* Show a negative GPE bar, but cut it off when it reaches the inner edge of the graph panel.
* When GPE<0, the total energy bar will be solid. (Mocked up two options -- gray and black)
* Add a GPE=0 reference line (to be mocked up with #127)
* Add white drop shadow to PEgrav label (or duplicate and offset text) so that it's visible when GPE<0. Outlining the text is problematic because the outline goes **inside** the text boundaries, which effectively makes it looks smaller.

Here's a side-by-side view of a small, positive GPE, and the equivalent amount of negative GPE. Because the value is small, the full height of the bar can be seen below the axis.
![screen shot 2017-09-29 at 4 42 18 pm](https://user-images.githubusercontent.com/8419308/31038645-3923bdb8-a535-11e7-9ca4-1753c5062581.png)

When dealing with a larger amount of GPE, the bar will need to be truncated when reaching the inner edge of the panel.
![screen shot 2017-09-29 at 4 50 44 pm](https://user-images.githubusercontent.com/8419308/31038868-5e286982-a536-11e7-8756-aef39b521e47.png)

Here are a few side-by-side options for the total energy bar. I prefer the gray bar, as the black looks a bit harsh, and the stroke-only may not project so well. Which do you prefer @ariel-phet @Denz1994?
![screen shot 2017-09-29 at 4 59 18 pm](https://user-images.githubusercontent.com/8419308/31039046-996650f8-a537-11e7-95df-0d4d0aff4177.png)

**Comment by Denz1994** [comment]
I like the gray bar. Nodes that are grayed out seem to be consistent in showing that the state of the node has changed (e.g. disabled buttons).

**Comment by ariel-phet** [comment]
I would agree with the gray bar @Denz1994 and @arouinfar lets go with that look.

**Comment by Denz1994** [comment]
Some changes have been made to the graph:

-BarNodes now extends below x-axis for negative values
-Zero point for the height can be adjusted
-Stroke around the labels has been added to stand out amongst negative barNodes.

**Comment by arouinfar** [comment]
@Denz1994 I think we can close this issue, as the energy graph now handles negative GPE. There is still some pixel polishing to be done to the energy graph, in general, but I think it seems appropriate to track that in a separate issue (which I'll open shortly).

@Denz1994 if you agree, please close.

**Comment by Denz1994** [comment]
Will do. Closing
