### ISSUE TITLE
Alternating spring constant causes spring to exceed normal limits

### ISSUE THREAD

**Issue by arnabp** [phetsims/masses-and-springs#170]
![masses_andsprings_constant_bug_1](https://user-images.githubusercontent.com/8583364/33405216-c258cfaa-d524-11e7-851c-642ace3a945b.gif)

I was able to recreate this by simply placing a weight and alternating between the smallest and largest spring constants. I got the spring to stretch to absurd lengths by pausing and having smallest constant at equilibrium position and largest constant at the lowest position for each cycle. But it's worth noting that it's not hard to reproduce simply by spamming left and right on the spring constant slider.  

![screen shot 2017-11-29 at 4 55 01 pm](https://user-images.githubusercontent.com/8583364/33405555-2154cd6e-d526-11e7-831e-703fb02c115b.png)

Mac OS X 10.12, Chrome 62, for phetsims/QA#67

Troubleshooting information (do not edit):
Name: ‪Masses and Springs‬
URL: https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.28/masses-and-springs_en.html
Version: 1.0.0-dev.28 2017-11-10 19:03:33 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Language: en-US
Window: 1920x1006
Pixel Ratio: 1/1
WebGL: disabled (Web page was not allowed to create a WebGL context. Web page was not allowed to create a WebGL context. )
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4918cd72","branch":"master"},"babel":{"sha":"fcbcac44","branch":"master"},"brand":{"sha":"53cf227b","branch":"master"},"chipper":{"sha":"ca18330e","branch":"master"},"dot":{"sha":"4a1ddd12","branch":"master"},"griddle":{"sha":"6e1983be","branch":"master"},"joist":{"sha":"f34dc747","branch":"master"},"kite":{"sha":"e4c0b773","branch":"master"},"masses-and-springs":{"sha":"9d24969e","branch":"master"},"phet-core":{"sha":"ad21faf3","branch":"master"},"phetcommon":{"sha":"d957aefc","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"8e5b0892","branch":"master"},"scenery-phet":{"sha":"11c7fdb3","branch":"master"},"sherpa":{"sha":"5079b265","branch":"master"},"sun":{"sha":"71295bf0","branch":"master"},"tandem":{"sha":"547eb84d","branch":"master"},"twixt":{"sha":"13905577","branch":"master"}}

**Comment by Denz1994** [comment]
This is a good catch. I have a few of ideas that may be workable solutions. 

1. Have the slider become inactive (grayed out) after the mass reaches a position that is "absurd". This way we can no longer adjust the spring constant after we reached an extreme.

2. Similar to option 1. We can make the slider inactive after the springExtention exceeds a range of "non-absurd"  values. This can be empirically determined and would reference the spring rather than mass position.

3. In an actual lab setting, we could only reproduce this bug by changing the physical properties of the spring at a rapid pace (a lab outside the scope of our target demographics I believe). At some point, the actual mass would hit the floor or table. We can have a psuedo-floor that exists way off the bottom-most part of the screen. It the mass's position reaches this point the spring stops (as if the springStopperButton was pressed) and returns to its equilibrium position. The equilibrium position would correspond to the current springConstant, as if we stopped the system's oscillation using the properties of the current spring system.

4. We could limit the spring's oscillation to the actual length of its material. In a lab, the spring could only extend as far as the material will allow it (based on its length). I'm thinking that the circumference of each ring on the spring added to the small tips at the ends of the spring could be its length. The spring must oscillate between the springLength * 2  (twice for each direction up and down). If it reaches an extreme it can return to its equilibrium position.

If @denz1994 had to choose I would pick option: 3,4,2,1 (best to worst). Option 3 favors the idea, of what could happen if a spring wasn't limited by the length of its material, while Option 4 takes this into account.

This does make me think if the spring wasn't limited by its length, wouldn't this bug technically be correct behavior? If so could we just let it be :-)

This is a really interesting bug. Thoughts @arouinfar  or @ariel-phet?

**Comment by ariel-phet** [comment]
@Denz1994 @arouinfar I do not really consider this behavior a bug

What @arnabp did does cause a situation that is not pedagogically useful, but the actions are also ones that are not really productive exploration. In essence, energy is being added to the system because if at the point of largest stretch you make the spring constant large, all of a sudden there is much more stored energy. 

Having the slider become inactive is generally to be avoided, unless there is a very obvious reason (for instance in FAMB the slider becomes inactive when the pusher falls off, there is a super obvious cue so the sim does not appear broken). 

I would lean towards just letting this be - sure a student can get to this place, but it is not breaking the sim, and it is not really doing any pedagogical harm. 

Let's see what @arouinfar says.

**Comment by arouinfar** [comment]
@Denz1994 thank you for thinking through some possible solutions. However, I agree with @ariel-phet that while this behavior may not be pedagogically productive, it is not actually a bug. I am also a bit wary of disabling the slider or otherwise limiting the sim, because that too would seem buggy, but would lack a clear physical explanation.

My vote is to leave the behavior as is, though make a note in the Tips.
