### ISSUE TITLE
Color Selection for Vectors

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#185]
This was brought up at the 01/04/18 status meeting by @terracoda:

> Colour note: Careful using Green and Yellow together. We discovered in Friction that these colours do not show enough contrast for some are note very distinguishable for some people with colour-blindness. Though you likely are not going with the yellow and green arrows.

> We used a blue in Friction instead of green.

I don't have any further thoughts on a suitable color. Thoughts @arouinfar?

**Comment by arouinfar** [comment]
Thanks for opening this issue @Denz1994! We use the same yellow and green for acceleration and velocity vectors in other sims (such as Pendulum Lab and Projectile Motion). In general, the contrast between the yellow and green is reasonable.
<img src="https://user-images.githubusercontent.com/8419308/34590030-8303fd5c-f171-11e7-83c0-4b0a56c91660.png" width=150> <img src="https://user-images.githubusercontent.com/8419308/34589966-221ec616-f171-11e7-8702-9bd097a34c02.png" width=150> <img src="https://user-images.githubusercontent.com/8419308/34589974-2c0fd4da-f171-11e7-8226-cd8e57db2f96.png" width=150> <img src="https://user-images.githubusercontent.com/8419308/34589981-330c4b42-f171-11e7-8cfc-c77a845e9c01.png" width=150>


However, I think there are perhaps too many green elements -- displacement, velocity, mass equilibrium position, and a mystery mass. I think we should find alternative colors for the latter two.The mass equilibrium (and equilibrium on Intro) could be black, but I'll need to play a bit more with the mockups to find an alternative color for the mystery mass, so leaving self-assigned.

**Comment by arouinfar** [comment]
@Denz1994 here are the updated colors:

* Equilibrium Position: ( 0, 180, 0 )
* Mass Equilibrium: black
* Small Mystery Mass: ( 246, 164, 255 )
* Medium Mystery Mass: ( 0, 222, 224 )
* Large Mystery Mass: ( 250, 186, 75 )

**Comment by Denz1994** [comment]
@arouinfar Could you review this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.45/phet/masses-and-springs_en_phet.html). Note that the mystery mass on the lab screen is unchanged because there it isn't labeled above. If these changes are sufficient then I'm leaving it up to @arouinfar to close.

**Comment by arouinfar** [comment]
Thanks @Denz1994! 

Here's what I'm seeing:
* Equilibrium Position icon & line: black, but should be green ( 0, 180, 0 )
* Mass Equilibrium icon: black 👍 
* Mass Equilibrium line: green, but should be black

I'd forgotten that the Lab screen had a different mystery mass was, since it was red. To confirm, there are four different mystery masses? The cyan mass on Intro and Lab appear to be the same to me.

Let's make the change the red mystery mass on the Lab screen to: ( 255, 120, 120 )

**Comment by Denz1994** [comment]
Yes, there are four different mystery masses. Also, you are correct the cyan mass on the intro and lab screens are the same.

Thanks for the second eye. The above changes were implemented in this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.47/phet/masses-and-springs_en_phet.html). Assigned to @arouinfar for review.

**Comment by arouinfar** [comment]
@Denz1994 everything's looking good now, though I have a few questions to bring up at design meeting.

1. Are the masses too muted? I think the gradient washes out the color a bit, so it ended up less saturated than I was expecting.  I still like the color change, but wonder if others have strong opinions otherwise.
![image](https://user-images.githubusercontent.com/8419308/35593569-74860138-05cd-11e8-9087-074cdf3f47ea.png)   ![image](https://user-images.githubusercontent.com/8419308/35593511-501c6cc4-05cd-11e8-8032-6bcedd393028.png)  ![image](https://user-images.githubusercontent.com/8419308/35593487-3dea1fec-05cd-11e8-857f-679e17c1dcda.png)  ![image](https://user-images.githubusercontent.com/8419308/35593474-36b9aa6c-05cd-11e8-8941-3f233f9f49b6.png)
![image](https://user-images.githubusercontent.com/8419308/35593166-638486f8-05cc-11e8-952c-9bdbb519dadc.png)
2.  Would it be better to have 5 unique mystery masses, rather than repeating the cyan mass? 
3. Do we want the '?' on all mystery masses?

It seems most appropriate to track 2 & 3 in a separate issue, so I'll open a new one.

**Comment by Denz1994** [comment]
1. I pushed this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.49/phet/masses-and-springs_en_phet.html) for review of the mass gradients. On the intro screen, the non-gray masses have had their gradients removed. On the other screens, the gradients have been darkened. A side effect of this hackish change means the gray masses have been slightly darkened as well, which I am not opting for.

2. Currently, the mass mystery mass values are: 
pink mass =  75g, cyan mass = 150g, orange mass = 200g, red mass = 125g

3. When I see the '?' on a mass it makes me think, "I should solve for this mass value." I don't know if the intro screen and vector screen is supposed to guide students to solve for a mass or if we want to trigger that thought on the first two screens. I think the lab screen is better suited to fit that idea of solving for a mass.

**Comment by arouinfar** [comment]
@Denz1994 I like the more saturated look in dev.49. The gray masses do look a bit darker, but we could probably lighten the underlying gray to improve the readability of the mass strings.

**Comment by arouinfar** [comment]
In design meeting, the team reviewed the colors used in dev.49 and liked the look. The decision was to use the darker gradient in dev.49, but lighten the underlying gray for the metallic masses so that they retain their original appearance. The same gradient should be applied to all masses.

**Comment by Denz1994** [comment]
The gray masses have been brightened a bit after the gradient changes. @arouinfar Can you review in this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.60/phet/masses-and-springs_en_phet.html)?

**Comment by arouinfar** [comment]
Looks great! Thanks @Denz1994.
