### ISSUE TITLE
?dev bounds have inconsistent width

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#186]
I've noticed that the width of the ?dev bounds is inconsistent.

Home screen matches other sims:
<img width="1033" alt="screen shot 2018-01-04 at 4 41 37 pm" src="https://user-images.githubusercontent.com/8419308/34589513-61bbb52a-f16e-11e7-8a79-c20dedf9c722.png">

However, ?dev is a bit narrower on the individual screens -- perhaps to preserve the aspect ratio?
<img width="1029" alt="screen shot 2018-01-04 at 4 41 47 pm" src="https://user-images.githubusercontent.com/8419308/34589530-792444b6-f16e-11e7-92a6-0cc6a60507b7.png">

For comparison, individual screens generally have the same ?dev width as the home screen, but it doesn't include the navbar.
![image](https://user-images.githubusercontent.com/8419308/34589632-fba3ca9c-f16e-11e7-81aa-8545d6336ed9.png)

@Denz1994 can you look into this issue? The ?dev bounds are very useful when it comes time to do some pixel polishing, so it'd be nice to have them properly sized.

**Comment by Denz1994** [comment]
I will look into this. Thanks for the report.

**Comment by Denz1994** [comment]
At some point during development, there was a change to the dev bounds for every screen. The change has been made so the sim is using the default layout bounds. However, this caused a heap of changes to many view elements and their positions.

This is all for the better though because there have been many generalizations and overall clean up of view elements.  If there are any other view changes that are odd it may be the change in the layout bounds in this issue.

Note: This includes modelViewTransform usages.
