### ISSUE TITLE
Disabling spring stopper buttons?

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#189]
In the spirit of reducing the visual heaviness around the panels as brought up in #172, the spring stopper buttons can be disabled when there isn't a mass attached. I think this is a natural behavior for the buttons. Thoughts @arouinfar?

P.S. Review changes in master. Merging of chipper 2.0 is delaying dev versions.

**Comment by arouinfar** [comment]
Excellent suggestion @Denz1994! The stop button is looking good on master, but I have one suggestion. It seems natural to also disable the stop button when the mass is at rest (since triggering the button won't do anything).

There are two scenarios to consider:
(1)  Immediately after using the stop button, the mass will be at rest.
(2)  In the presence of damping, the oscillation will eventually die off. The stop button should become inactive once the velocity and/or amplitude (up to @Denz1994) is zero. 

Scenario (1) should be pretty straightforward, but scenario (2) may have some floating point issues that need to be accounted for.

**Comment by Denz1994** [comment]
Thanks for the feedback. I will toil with scenario (2). This may also help to solve #188. Ideally, if the mass velocity = 0 m/s and the center of mass is at the mass equilibrium position the button should be disabled. This may be implemented in Mass.js.

**Comment by Denz1994** [comment]
The spring stop button is only enabled when a mass is oscillating. Otherwise, we shouldn't need to stop the spring. Could you review in master @arouinfar and update this issue as needed?

**Comment by arouinfar** [comment]
Looks great @Denz1994!!

**Comment by arouinfar** [comment]
>  But of course, I'm pretty confident that it should become disabled the moment the mass is grabbed, not the moment it is released. Right @arouinfar?

Agreed @phet-steele. Great catch!

**Comment by Denz1994** [comment]
Good catch. See if master is fixed @phet-steele.

**Comment by phet-steele** [comment]
Works great, thanks.
