### ISSUE TITLE
OneSpringView shelf should be shifted over.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#196]
While reviewing #190, @ariel-phet mentioned that the shelf on the energy and lab screen should be shifted to towards the play area a bit more. There is some overlap with the masses on the Lab Screen and on the Energy Screen, the spacing is a bit tight.

**Comment by arouinfar** [comment]
@Denz1994 it looks like the shelf was moved between [dev.33](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.33/masses-and-springs_en.html) and [dev.34](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.34/masses-and-springs_en.html).  In [dev.35](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.35/phet/masses-and-springs_en_phet.html) the Energy Graph panel was shortened to make room for the shelf.

Given the changes in #186, the spacing may not be quite so tight anymore. I would prefer that the Energy Graph fill the entire vertical space, as it did previously. 

I would recommend you: 
* Increase length of Energy Graph so that it is bottom-aligned with the shelf
* Shift the shelf to the right a bit (~50 px) so it doesn't overlap with Energy Graph
* If things look a bit cramped, reduce the width of the shelf a few px.
