### ISSUE TITLE
Masses "drop into place" on startup...consider removing? 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/masses-and-springs#211]
Currently, when you start the sim, or switch between the scenes on the first screen, the masses "drop into place" - this seems to be a repetition of the way the original runs. And the masses in the original make a "clunk" sound when they hit.

Generally, we don't have things animate on sim startup. I also think the design of the current sim has no issues with users realizing they can hang the masses on the springs. Can we consider removing this initial animation on all screens/scenes? I am not sure what purpose it is serving.

**Comment by Denz1994** [comment]
This [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.52/phet/masses-and-springs_en_phet.html) removes the "drop into place" motion for review. 

I remember a part of the discussion around this "drop into place" motion was to differentiate the masses on the intro screen when switching scenes on the intro screen and when pressing the reset button. At some point, we decided to reset the masses when switching scenes so that isn't a concern anymore.

**Comment by ariel-phet** [comment]
@Denz1994 excellent thanks. I prefer that behavior. Will defer to @arouinfar .

**Comment by arouinfar** [comment]
Thanks @Denz1994! I prefer to remove the "drop into place" startup animation, as it's a bit dated. I think the fall-then-zoom animation in #133 captures a lot of the original intention behind animating the falling masses on startup.  

I suspect @kathy-phet may have strong opinions about this issue, so I think it'd be best to decide in today's design meeting.

**Comment by Denz1994** [comment]
I believe the consensus was to remove this "drop into place" animation. This is removed from the latest dev and on master. Leaving up to @arouinfar to close.

**Comment by arouinfar** [comment]
Correct @Denz1994. In design meeting @kathy-phet confirmed that the original intent of the animation was to cue that the masses were grabbable, so it's no longer necessary. Closing.
