### ISSUE TITLE
Combine Length and Constant Parameter panels

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#214]
@Denz1994 in the spirit of #108, let's combine the Length and Constant Parameter panels for the 2nd scene on Intro. I've mocked it up, with the font sizes requested in #205.

![image](https://user-images.githubusercontent.com/8419308/35693894-d8dfbd8e-073c-11e8-9a60-ead9881ff36b.png)

![image](https://user-images.githubusercontent.com/8419308/35693878-cc75aa5e-073c-11e8-89b0-9764ded3fd9f.png)

**Comment by Denz1994** [comment]
I really like this suggestion. Thanks for the input @arouinfar.

**Comment by Denz1994** [comment]
Could you review this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.54/phet/masses-and-springs_en_phet.html). There are some alignment and font issues detailed in #205.

Are we changing the title of the panel? I see in the mockup "Length 1" instead of "Spring Length 1"? If this is fine I'll leave it up to you to close.

**Comment by arouinfar** [comment]
Looks good @Denz1994! Since #205 is still underway, I won't worry too much about font sizes.

>  I see in the mockup "Length 1" instead of "Spring Length 1"? 

Good catch! I had considered adding a "Spring 1" title to the panel itself, but then decided against it because it felt a bit too heavy. I forgot to revert "Length" to "Spring Length" before taking the screenshots for this issue.
