### ISSUE TITLE
Mystery Mass Mechanics

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#218]
In design meeting, we discussed the goals and productive constraints for the mystery masses.

Intro & Vectors: 
* Mystery masses have the same density as known masse
* Values are all within the range of the known masses, to support qualitative comparisons.

Lab
* Masses should be different from Intro & Vectors
* Mystery masses should not have the same density as the known mass (or each other). The smaller mass will be heavier, and larger mass will be lighter.
* One mass should be larger than 300 g so that students cannot quantitatively determine its mass by comparing the displacement to the known mass.
* Masses should not be divisible by 25g, as they are on the Intro screen.

@Denz1994 please make the following changes:
- [x] Add '?' to the mystery masses on Intro and Vectors (to be consistent with Lab)
- [x] Red mass on Lab: keep its current size, but change value to 370 g
- [x] Cyan mass on Lab: keep its current size, but change color to rgb(128, 197, 237) and value to 230 g

**Comment by Denz1994** [comment]
The above changes have been applied. @arouinfar please review in this [dev version]( https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.57/phet/masses-and-springs_en_phet.html).

Note to self: Masses should be initialized in each screen's model. Generalization, in this case, is a bit cumbersome. Review TODO statements.

**Comment by arouinfar** [comment]
@Denz1994 can you double check the values of the Lab screen mystery masses? 

The blue mass looks like it's slightly under 230 g. (Movable line is in the same place for both.)
![image](https://user-images.githubusercontent.com/8419308/35992934-ff7901bc-0cc8-11e8-9233-6f73da53185f.png) ![image](https://user-images.githubusercontent.com/8419308/35992947-0aabbfd4-0cc9-11e8-994a-6da5c62cfca0.png)

The red mass appears to be less than 300 g. (Movable line is in the same place for both.)
![image](https://user-images.githubusercontent.com/8419308/35993112-8b7aa3d2-0cc9-11e8-9d7b-940f00416938.png)  ![image](https://user-images.githubusercontent.com/8419308/35993137-99f4837e-0cc9-11e8-9d20-55cbe2b04e35.png)

I'm also wondering if the introduction of masses with different densities somehow affected the other masses, because they are looking a bit smaller (or maybe the label is just larger?). Compare dev.54 and dev.58:
 ![image](https://user-images.githubusercontent.com/8419308/35993237-e3383ddc-0cc9-11e8-934a-1edeccfa3f1f.png) ![image](https://user-images.githubusercontent.com/8419308/35993205-d1897042-0cc9-11e8-8336-0f30c3c7176d.png)

**Comment by arouinfar** [comment]
@Denz1994 did you intentionally assign me? I took a look at master, and there doesn't appear to have been any changes made.

**Comment by Denz1994** [comment]
In regards to the mass values above. If all of the densities are the same then we get something that looks like this:
![image](https://user-images.githubusercontent.com/13894380/36109760-5943ecac-0fee-11e8-8166-24b69b33b7a4.png)![image](https://user-images.githubusercontent.com/13894380/36109823-8226e7e6-0fee-11e8-8cca-21b8bd628b1c.png)

In the above comparison, the moveable line is in the same location. Here the lines don't match up exactly because the hook sizes are slightly different. The reason for this is because the hook size is static and is determined at the mass's initialization. The gold mass is initialized at 100g (smaller hook) and the blue mass is initialized at 230g.

Personally, I think this approach of determining the hook height, creates an inconsistency in using the adjustable mass to gauge the mass of the other masses. I thought this was a good approach so students don't "cheat" into finding the mass using the massValue of another mass.

Alternatively, we can dynamically adjust the hook height, but it may not be necessary. 

In this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.61/phet/masses-and-springs_en_phet.html), the text on the label was reverted and the values for the masses are labeled. The order of the densities of the masses from smallest to largest: gold, blue, red. 

Could you review this [dev version ](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.61/phet/masses-and-springs_en_phet.html)@arouinfar?

**Comment by Denz1994** [comment]
@ariel-phet added input in a zoom meeting: 02/13/18

> Each mass should have the same hook height. The hook height for a 100 g mass looks good to use.

I will update and post a new dev version.

**Comment by Denz1994** [comment]
The hook heights have been adjusted and the masses have had their appropriate labels applied. Could you review this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.65/phet/masses-and-springs_en_phet.html) @arouinfar?

**Comment by arouinfar** [comment]
@Denz1994 thanks for the clarification. The hook size looks great in dev.65, but I think something's still not quite right with the masses. 

The blue mass still appears to be less than 230 g (movable line in the same place for both):
![image](https://user-images.githubusercontent.com/8419308/36235067-b3bd61e0-11ab-11e8-87f1-3256e3c9fa9a.png)  ![image](https://user-images.githubusercontent.com/8419308/36235060-ab941d6a-11ab-11e8-8f11-e129ead76e9f.png)

You may also want to double check that the red mass is 370 g. Its displacement looks a bit too small.

**Comment by arouinfar** [comment]
@Denz1994 did you still want to talk about this? I pulled master, and things are looking the same.

**Comment by Denz1994** [comment]
In a zoom meeting with @ariel-phet, we reviewed the offset of the mass equilibrium lines. It seems to be a natural cause of having differently sized masses despite having the same mass value. The mass equilibrium line is tracking the center of mass and if the massNodes are varied in size, the line should be in a different position.

Leaving to @arouinfar to close if needed.

**Comment by arouinfar** [comment]
>  It seems to be a natural cause of having differently sized masses despite having the same mass value. 

I can't believe I didn't take the varying densities into account! <i>Of course</i> the mass equilibrium will be shifted slightly. I reviewed again, this time comparing the Displacement vector (as I should have been doing this whole time), and everything is matching up perfectly.
