### ISSUE TITLE
Elastic potential energy should only depend on displacement

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/masses-and-springs#221]
On the energy screen, it looks like the elastic potential energy is not being calculated correctly from the equilibrium position. For instance for default conditions on the energy screen a (100 g mass, default spring constant) a 20 cm displacement cause a larger PE_elastic for a stretch than a compression. 

Seen on [1.0.0-dev.54](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.54/phet/masses-and-springs_en_phet.html)

Probably a quick fix, but high priority.

**Comment by arouinfar** [comment]
@ariel-phet @Denz1994 I don't believe that the current behavior is incorrect.

I've had similar thoughts about the displacement. It appears to be asymmetric around the mass equilibrium (larger stretch than compression) because the displacement vector references the <i>natural length</i>. The oscillation itself, however is symmetric about the equilibrium position.

For example, at equilibrium the bottom of the mass is at the 30 cm mark. At the max/min of the oscillation, the bottom of the mass is at 10 cm and 50 cm, respectively. The displacement about equilibrium is symmetric, but the displacement vector is tied to the displacement from its natural length (consistent with Hooke's Law).
![mas_symmetry](https://user-images.githubusercontent.com/8419308/35936463-93467ccc-0c00-11e8-8ea4-e9a7bb2a8a55.gif)

Often, a horizontal spring is used to introduce Hooke's Law and elastic potential energy. In that situation, the natural length and the equilibrium position are the same. 
![image](https://user-images.githubusercontent.com/8419308/35936881-ccca6f84-0c01-11e8-901b-d4bcbb8dce29.png)

However, gravity muddies the waters a bit. The elastic potential energy is the integral of the spring force, and the "x" in the spring force is the displacement from the spring's natural length.
![image](https://user-images.githubusercontent.com/8419308/35936730-4fb685c8-0c01-11e8-913a-1aa25808eb54.png)

Repeating the experiment above with g=0 reveals the symmetric displacement (and EPE) that one might expect.
![mas_symmetry_0g](https://user-images.githubusercontent.com/8419308/35937210-bf9f3956-0c02-11e8-8ef3-12d512d8b6c1.gif)

**Comment by arouinfar** [comment]
@ariel-phet I've made a note in #174 to add the following to the Teacher Tips:

> Students may notice that the displacement vector appears to be asymmetric about the mass equilibrium (greater stretch than compression). This is because the zero point of the displacement vector is at the spring's natural length. Setting the gravity to zero will reveal a symmetric displacement vector about the mass equilibrium.

If you've been convinced that there isn't an issue with the model, please feel free to close.

**Comment by ariel-phet** [comment]
@arouinfar, please note in the original comment, I am not discussing the displacement from equilibrium, it makes sense with the gravity on, the displacement will be asymmetric due to the gravitational potential energy. 

The issue with the model is in the energy ***displayed on the energy graph*** Try the same experiment manually stretching 20 cm, and compressing 20 cm passed the natural length position and you will see that the energy graph is not showing the same value for elastic potential energy. This PE should only depend on the displacement from natural length. Let me reiterate, I am not talking about oscillation, purely the displayed value of PE_elastic for equivalent stretch and compression.

**Comment by ariel-phet** [comment]
Notice 20 cm stretch
![20cm stretch](https://user-images.githubusercontent.com/4051174/35941062-50fa6730-0c0e-11e8-8a30-1148e84ecfa1.PNG)

20 cm compression
![20 cm compression](https://user-images.githubusercontent.com/4051174/35941080-59e9ce08-0c0e-11e8-8e58-7343da11a394.PNG)

**Comment by ariel-phet** [comment]
@arouinfar please note that in the above screenshots that for the ***equivalent displacement from natural length*** the bar graph is displaying different value of PE_elastic

**Comment by arouinfar** [comment]
@ariel-phet thanks for the clarification -- sorry I misinterpreted your original comment. Looks like we were in the process of testing the same scenario. The gravitational potential energy is indeed asymmetric about the natural length. 
![image](https://user-images.githubusercontent.com/8419308/35941383-437b2d64-0c0f-11e8-85f5-dfc2a39d4cd3.png)

It seems like there's something strange going on with the displacement, which is throwing off the EPE magnitude. For example, when stretching this spring, the displacement goes in the wrong direction, at first. (Demonstrated at g=0 so displacement would be zero when at equilibrium.)
![displacement](https://user-images.githubusercontent.com/8419308/35941905-1f3a93ac-0c11-11e8-90a1-2afd8dbe9f27.gif)

Back to @Denz1994 for investigation.

**Comment by Denz1994** [comment]
The slight offset has been removed from the displacement arrow and the asymmetry in the Elastic Potential Energy is fixed. There was an issue with the modelViewTransform that was being used for the displacement vector.

Could @ariel-phet verify the issue has been corrected in this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.66/phet/masses-and-springs_en_phet.html)?

**Comment by ariel-phet** [comment]
Verified fixed. Nice job. Closing.
