### ISSUE TITLE
Reduce opacity of unselected scene a bit more?

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/masses-and-springs#237]
When looking at 1.0.0-dev.81, to my eye, pretty much everything is looking quite clean and polished

The one thing I noticed as a possible tweak was decreasing the opacity of the unselected scene on the intro screen. It just seems a bit dark to me. 

![scene select](https://user-images.githubusercontent.com/4051174/36752768-5160fcf8-1bc1-11e8-9895-50175248ea5d.PNG)

**Comment by ariel-phet** [comment]
@arouinfar if you agree, feel free to assign back to me and I will work with @Denz1994 to tweak it.

**Comment by arouinfar** [comment]
Great catch @ariel-phet. It definitely looks a bit dark, especially when comparing to Hooke's Law:
![image](https://user-images.githubusercontent.com/8419308/36753781-78a36f64-1bc4-11e8-95e5-ae83e6fecf7b.png)

It looks like @Denz1994 may be layering a reduced-opacity black square on top of the unselected scene, rather than reducing the opacity of the button itself.

**Comment by Denz1994** [comment]
@arouinfar Nope, no black square being layered here. I just needed to reduce the opacity of the deselected radio button from the default value. Could you review this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.85/phet/masses-and-springs_en_phet.html)?

**Comment by arouinfar** [comment]
:+1:
