### ISSUE TITLE
User request: millimeter ruler

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/masses-and-springs#262]
> I am new to teaching physics and I love the simulations.  I am using the springs and masses simulation and was wondering if you would consider using a millimeter meter stick instead of a centimeter measure?  We use mm only tape measures now in engineering and 3D printing and it makes sense to use powers of 3 only for prefixes.  Just wondering if it could be done.  Thank you for your work.  These are great.

**Comment by Denz1994** [comment]
Visually the tick marks may be too dense to differentiate.

**Comment by arouinfar** [comment]
@oliver-phet the scale of the masses and spring constants is typical for what is found in a physics lab, so the displacements are on the order of centimeters. As @Denz1994 pointed out, users would not be able to resolve mm tick marks on the ruler.  

In this context, it's generally better to convert the cm to m when doing calculations (finding k or unknown g), because the SI unit for forces is N, which requires kg and m. If the teacher prefers to use mm, perhaps they can direct their students to convert the cm to mm. It sounds like the course is for high school students, so unit conversion would not be an inappropriate skill.

**Comment by oliver-phet** [comment]
Replied to user. Closing.
