### ISSUE TITLE
Period trace doesn't fade when step forward is held

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#269]
1. Lab screen, attach a mass, enable Period Trace and let it start drawing.
2. Pause the sim before the period has finished.
3. Hold Step Forward and eventually the trace will just disappear instead of fade away.

![mas14](https://user-images.githubusercontent.com/5863899/40335058-00beea2c-5d1f-11e8-913b-3048507ae80f.gif)

Seen on macOS 10.13.4 Chrome. For phetsims/QA/issues/122.

<details>
<summary>Troubleshooting Information</summary>

URL: https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.102/phet/masses-and-springs_all_phet.html
Version: 1.0.0-dev.102 2018-05-21 16:49:55 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4ce9d171","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"aaa0d77a","branch":"master"},"dot":{"sha":"070374e3","branch":"master"},"griddle":{"sha":"f9afbaec","branch":"master"},"joist":{"sha":"0d2b102d","branch":"master"},"kite":{"sha":"bd06199c","branch":"master"},"masses-and-springs":{"sha":"577e8758","branch":"master"},"phet-core":{"sha":"49911783","branch":"master"},"phet-io":{"sha":"545d86c9","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5204ea8e","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"ccaaaa4b","branch":"master"},"phet-io-wrappers":{"sha":"1b254bcf","branch":"master"},"phetcommon":{"sha":"9a8756e6","branch":"master"},"query-string-machine":{"sha":"f9def230","branch":"master"},"scenery":{"sha":"588f22fb","branch":"master"},"scenery-phet":{"sha":"b31317ca","branch":"master"},"sherpa":{"sha":"ded365aa","branch":"master"},"sun":{"sha":"9ebf1a6c","branch":"master"},"tandem":{"sha":"beb7d180","branch":"master"},"twixt":{"sha":"756c0bd8","branch":"master"}}
</details>

**Comment by Denz1994** [comment]
This one was tricky. The period trace now fades when the sim is playing, in its final state (last leg of trace), and has already begun fading.

I have gained a new appreciation for encapsulation and good documentation. Test in master @phet-steele.

**Comment by Denz1994** [comment]
Note to @phet-steele: The period trace doesn't fade when the sim is stepped through using the stepForwardButton. This behavior is found in Pendulum Lab as well.

**Comment by ghost** [comment]
@Denz1994, I tested in master. The period trace doesn't disappear at all now.

![ms](https://user-images.githubusercontent.com/31285590/40510454-fec2c5d0-5f59-11e8-8008-27522dfed5a7.gif)

**Comment by Denz1994** [comment]
I think this is more of a question of design. The period trace is designed after pendulum lab and doesn't fade when the sim is paused. 

My two cents: After a period trace is completed it takes a few oscillations to represent a new trace, during this time it is fading. I don't think we want the period trace to continuously follow the mass's oscillation pattern, otherwise, we wouldn't have the fading part. So having a period where the fade is delayed wouldn't be a problem in my book. Is this a new feature that we want in this sim? If it is a bug here, it may be a bug in Pendulum Lab.

Personally, it would be sort of a pain to refactor this again. I don't mind crunching through it, but I just want to make sure it is justified.

Tagging @ariel-phet for input.

**Comment by ariel-phet** [comment]
@Denz1994 @lmulhall-phet I chewed on this for a bit.

1. This is the same behavior as published pendulum lab (period trace not fading when using step forward)

2. Thanks for noticing this behavior @lmulhall-phet 

3. Although this behavior is a bit odd, it really only makes a difference if you are watching the evolution of the sim ONLY through the step forward button. Generally such a button is used to see a specific moment in the sim. I think if you have lots of damping and were watching the evolution of the sim with the step button this would look a bit odd, since the non-fading trace would get out of sync with the behavior. However, this is not really a productive way to use the sim.

Considering this behavior matches pendulum lab, there are no user reported issues with that behavior, and the oddness would come in a very edge-case use of the sim that I do not feel is particularly productive, I think we can go with "won't fix"

Closing
