### ISSUE TITLE
Strings scaled down too much despite adequate white space

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#296]
For https://github.com/phetsims/QA/issues/129

For i18n, strings shrink when they reach their max width. Several strings in MAS seem to have shrunken quite a bit despite adequate white space. @Denz1994 it looks like there may be some issue with the max width.

Here are a few notable examples:

* Mass has quite a bit of white space to its right.
<img src="https://user-images.githubusercontent.com/8419308/41555366-b9b5a8d2-72f4-11e8-8c2e-50220a604ac8.png" width=300>  <img src="https://user-images.githubusercontent.com/8419308/41555341-a78888b4-72f4-11e8-8c30-bd51a01df6f7.png" width=300>

* Movable Line, Period Trace, Gravity, Damping, and Velocity all seem way too small given how much blank space they have to their right.
<img src="https://user-images.githubusercontent.com/8419308/41555451-fb80cc9c-72f4-11e8-8678-ed33826b7995.png" width=300>  <img src="https://user-images.githubusercontent.com/8419308/41555650-93c66ca0-72f5-11e8-8632-2ef0ca5e77cf.png" width=300>

**Comment by Denz1994** [comment]
These maxWidths have been adjusted so they are more reasonable for the length of their text to remove white space. @arouinfar Does master look good?

**Comment by arouinfar** [comment]
@Denz1994 the maxWidths are looking better, but Mass, Gravity, and Damping all still look a bit small.

![image](https://user-images.githubusercontent.com/8419308/41877917-50061de4-7890-11e8-97ca-56597ac5d4b8.png)
![image](https://user-images.githubusercontent.com/8419308/41877939-6362cda6-7890-11e8-9d86-6ac8e0d5bfd2.png)

I'll think we should limit Height's maxWidth so the string doesn't run into the play/pause/step buttons.
![image](https://user-images.githubusercontent.com/8419308/41877948-6d00a5c2-7890-11e8-8a0e-67fcfdbbcd1a.png)

**Comment by Denz1994** [comment]
The reason the Gravity and Damping look smaller on the lab screen is due to the title of the number control being private in common code. The panel has to fit the title, white space, and readout for a number control and there isn't much room to play with after that. The same is true for the massValueControlPanel.

This is different in Pendulum Lab because it is using a customized NumberControl for that sim. I can't use it in this case because there are different alignments with the sliders being indented and an icon is added for the massValueControlPanel.

I can work towards building a custom NumberControl, but it would be a significant refactor. I don't want to seem like I'm opting out, but I'm leaning against making the refactor this late into development. 

Other than that some more pixel polish alignments were made and max width adjusted to fit stringTest=double, stringTest=long and stringTest=rtl. Thoughts @arouinfar?

**Comment by arouinfar** [comment]
@Denz1994 let's not bother with a custom NumberControl. I'm hopeful that #293 will provide Gravity and Damping with a bit more space to expand.
