### ISSUE TITLE
TypeError: Cannot read property 'width' of undefined

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#321]
Upon sim load:

```
Uncaught TypeError: Cannot read property 'width' of undefined
    at new VerticalCheckboxGroup (masses-and-springs_all_phet_debug.html:119776)
    at new LineVisibilityNode (masses-and-springs_all_phet_debug.html:126056)
    at new IntroScreenView (masses-and-springs_all_phet_debug.html:127462)
    at IntroScreen.createView (masses-and-springs_all_phet_debug.html:127556)
    at IntroScreen.initializeView (masses-and-springs_all_phet_debug.html:125274)
    at Array.<anonymous> (masses-and-springs_all_phet_debug.html:134300)
    at masses-and-springs_all_phet_debug.html:134308
```

Only in 1.0.0-rc.4, not in master. Seen on Win 10 Chrome.

<details>
<summary>Dependencies</summary>

{
  "comment": "# masses-and-springs 1.0.0-rc.4 Wed Aug 22 2018 12:28:19 GMT-0600 (MDT)",
  "assert": {
    "sha": "928741cfc8fe804334d5b35292140314511f8678",
    "branch": "HEAD"
  },
  "axon": {
    "sha": "37d5839cf25343fec5811fefd088eeb510b8950b",
    "branch": "HEAD"
  },
  "brand": {
    "sha": "89d28f6309a83eb51b6c1fc0130e76ad7935f09e",
    "branch": "HEAD"
  },
  "chipper": {
    "sha": "bc1f66fea88338fb61de4aad469470909a0e2281",
    "branch": "HEAD"
  },
  "dot": {
    "sha": "bd4d703525b862fef1633d6fda144c47c8827945",
    "branch": "HEAD"
  },
  "griddle": {
    "sha": "7be25724b51058d5903926a187be129866ec5f11",
    "branch": "HEAD"
  },
  "joist": {
    "sha": "8da47b067f4a8b7c74f857c6a16c70022f07096b",
    "branch": "HEAD"
  },
  "kite": {
    "sha": "3b76b24ad32130fff69790f1a595a4a0b9d6dd1f",
    "branch": "HEAD"
  },
  "masses-and-springs": {
    "sha": "d8dd5f6aacc34d24f357bff83b42806ffbae325c",
    "branch": "HEAD"
  },
  "phet-core": {
    "sha": "e0cec207f36f211f56382ea1897f007110284e46",
    "branch": "HEAD"
  },
  "phet-io": {
    "sha": "e5c7148f3344b343b57fe7108a902facd1d875ec",
    "branch": "HEAD"
  },
  "phet-io-wrapper-classroom-activity": {
    "sha": "5204ea8e3d83eabff4d8b877f49171a90d704585",
    "branch": "HEAD"
  },
  "phet-io-wrapper-lab-book": {
    "sha": "ccaaaa4b4b36fb8ae30d033262443965077649f2",
    "branch": "HEAD"
  },
  "phet-io-wrappers": {
    "sha": "f3701e8d52f8b67db016f549ee07cb63362c7104",
    "branch": "HEAD"
  },
  "phetcommon": {
    "sha": "80414edbe26f41b5f5544377c2dae03a8cca9922",
    "branch": "HEAD"
  },
  "query-string-machine": {
    "sha": "1f2322e4cab5658d4134715f00e12e5a741b2b9f",
    "branch": "HEAD"
  },
  "scenery": {
    "sha": "3b05db543840cd399fa9438b46603d6e77076ce2",
    "branch": "HEAD"
  },
  "scenery-phet": {
    "sha": "f37bff38730ed9d5d6182768a44c52f4a3637f62",
    "branch": "HEAD"
  },
  "sherpa": {
    "sha": "ded365aa2df5026200b20b13b9a9027d5a25215e",
    "branch": "HEAD"
  },
  "sun": {
    "sha": "00b9c74c4b94ea7b5871a3afe5b59d49d9ea2fca",
    "branch": "HEAD"
  },
  "tandem": {
    "sha": "3e1c8fd37ccbf76ac00e147ef6fb1edddbbbab8c",
    "branch": "HEAD"
  },
  "twixt": {
    "sha": "050e8f19b2368497931bce2e5429825aa0938eff",
    "branch": "HEAD"
  }
}
</details>

**Comment by Denz1994** [comment]
This was fixed with some help by @jonathanolson and @samreid. The issue was due to a bad set of shas being mixed into the dependencies of the rc.4. The approach involved reverting some SUN dependencies 7b8858ebcd5e159a3947c0b3f4d03d16720b1f91, a correction to Sherpa preloads (ad696015207cc1126fd019f35f3d1a0c44b881ac) and recommiting corrections applied to this rc version (35251180aca96ec5279be59c3cbeb3d8d239cdcf, b2785338dd8e030a30a2d69b1727c50f6afc11d4, 65541587e195acff8c7e7937c95c24831d33584c, 1a81457a55b5b8c7d2170b50a8c4b162520632f5, 02dfd061fdbb0ee70366cb1a5dd955c796f39522, and 0cd2d603742736891a8911ee067dce469005e814). 

A successful rc.4 is found here at this link for  [1.0.0-rc.4](https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-rc.4/phet/masses-and-springs_all_phet.html).

Note to self: Going forward it is advised not to merge master into the rc branch. See "Manual maintenance patching" in https://github.com/phetsims/phet-info/blob/master/deployment-info/chipper-2.0.md.
