### ISSUE TITLE
Radio buttons change position in Spanish translation 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/masses-and-springs#357]
This radio buttons and strings move position in the Spanish version of the sim:

![image](https://user-images.githubusercontent.com/26031501/78204234-54fb8280-7456-11ea-8ade-71acdabab85e.png)

This panel appears when this option is selected:
![image](https://user-images.githubusercontent.com/26031501/78204515-f387e380-7456-11ea-8d11-97fb54b04aec.png)

**Comment by Denz1994** [comment]
It looks like this is as extreme on Master, but is apparent on the 1.0 branch. I adjusted these radio buttons to both use the same options. It is looking better after these changes but we'll have to revisit on the next deploy or QA cycle.

**Comment by Nancy-Salpepi** [comment]
For https://github.com/phetsims/qa/issues/936
This looks fixed in 1.1.0-dev.2 using ?locale=es. I also tried a few other locales and location of the radio buttons/text look good.

@jbphet one question I have is why the word "Springs" in double curly brackets is appearing in locales other than English? Isn't the text ("Spring Constant") the same in published and current versions? 


<img width="238" alt="Screenshot 2023-06-02 at 2 18 11 PM" src="https://github.com/phetsims/masses-and-springs/assets/87318828/63c3907c-c0d0-43dd-bfd6-4fabaa748f1c">

**Comment by jbphet** [comment]
@Nancy-Salpepi asked:

 > [W]hy the word "Springs" in double curly brackets is appearing in locales other than English?

Good observation.  This is exactly why we need to republish from master and fix up the strings in the process.  Some changes were made between the publication of MAS and MASB that broke things like this.  More details are available in https://github.com/phetsims/masses-and-springs/issues/381.

I think, since we have another issue tracking the `{{spring}}` problem, that it's okay to close this one.  Agreed @Nancy-Salpepi?

**Comment by Nancy-Salpepi** [comment]
Thanks for explaining @jbphet. The radio buttons look good, so closing.
