### ISSUE TITLE
The clear thermal button disappeared

### ISSUE THREAD

**Issue by samreid** [phetsims/masses-and-springs#371]
In https://github.com/phetsims/scenery-phet/issues/746, we discovered that Masses and Springs creates but never displays a MoveToTrashButton.  The sim used to look like this:

https://github.com/phetsims/masses-and-springs/issues/322#issue-353233485

<img width="327" alt="image" src="https://user-images.githubusercontent.com/679486/176188652-dea552e1-cf43-4342-98d7-7d9438c6ef1c.png">

But now looks like this:

<img width="207" alt="image" src="https://user-images.githubusercontent.com/679486/176188791-2d103f4b-ec0c-4a65-9d13-af8dbe5eef47.png">

In https://github.com/phetsims/griddle/issues/49 there was this commit: https://github.com/phetsims/masses-and-springs/commit/50f69eb9ec6e0ac7f057e4179c102fc70201f809 which removed the clear button, but without explanation and it's not clear that was intentional.  @jessegreenberg can you please comment?

**Comment by jessegreenberg** [comment]
Oh no! That deletion was not intentional, I reviewed https://github.com/phetsims/griddle/issues/49 and it was all about changing the label colors, changes were meant only for `labelColor` in https://github.com/phetsims/masses-and-springs/commit/50f69eb9ec6e0ac7f057e4179c102fc70201f809.

The button has been added back. Thanks for finding this.

**Comment by samreid** [comment]
Looks great, thanks for the fix.  Closing.
