### ISSUE TITLE
Stop symbol is no longer red when button is disabled 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/masses-and-springs#379]
**Test device**
MacBook Air M1 chip

**Operating System**
13.4

**Browser**
Safari 16.4

**Problem description**
For https://github.com/phetsims/qa/issues/936 and https://github.com/phetsims/qa/issues/937, when the Stop button is disabled, the Stop symbol is no longer red. It is now gray. 

**Visuals**
Published: 
<img width="268" alt="Screenshot 2023-06-12 at 8 15 05 AM" src="https://github.com/phetsims/masses-and-springs/assets/87318828/d3c62d36-cc43-4211-be66-44d671abd633">

Current dev version:
<img width="268" alt="Screenshot 2023-06-12 at 8 06 07 AM" src="https://github.com/phetsims/masses-and-springs/assets/87318828/bdf563a0-56d7-48fe-9b06-ca6a2f4f0ed2">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Masses and Springs‬
URL: https://phet-dev.colorado.edu/html/masses-and-springs/1.1.0-dev.2/phet/masses-and-springs_all_phet.html
Version: 1.1.0-dev.2 2023-05-02 23:06:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language: en-US
Window: 1464x775
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by arouinfar** [comment]
Nice attention to detail @Nancy-Salpepi.

In https://github.com/phetsims/sun/issues/658 we added support for "grayscale when disabled" to sun buttons and made it the default behavior. Previously, disabling a button would have only changed its opacity.

I prefer the grayscale look in Masses and Springs. There's a more significant visual change when the button becomes enabled, which brings more attention to itself. The stop buttons are very useful, but initially disabled (because nothing is oscillating at startup) so I think it's helpful to make the disabled > enabled switch more dramatic.
