### ISSUE TITLE
Are mass colors using color blind colors?

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#49]
Masses are using red, green, and blue colors. Should we incorporate phetColorScheme.COLORLIND?

**Comment by Denz1994** [comment]
The design doc doesn't mention any specifics regarding this. The differences in the view are listed below.

**Default Colors**
![image](https://cloud.githubusercontent.com/assets/13894380/23861973/5876fe0c-07d1-11e7-878c-cd0a1fd84a10.png)

**Color Blind Colors Enabled**
![image](https://cloud.githubusercontent.com/assets/13894380/23862074/a7c64a44-07d1-11e7-8c2a-8579a020422f.png)

Is there a general rule for Phet Sims, when we should and shouldn't use color blind colors?

**Comment by Denz1994** [comment]
As suggested by @jbphet, the color-blind scheme should be used. Using a Chrome plugin for color-blindness, we noticed the masses are distinct enough for several forms of color-blindness.

With further discussion on this topic, we came to the conclusion that Phet-IO instrumentation should be careful to consider color blindness with instrumenting tandem IDs. Tandem IDs should not specify color, as users may have different interpretations for colors.

Logging a separate issue to double-check this consideration and closing this current issue.

**Comment by Denz1994** [comment]
This should also be considered for the reference lines and the spring stopper buttons as well, I assume.

Do you have any input on this change @arouinfar?

**Comment by Denz1994** [comment]
**Color-Blind Scheme Enabled**

![image](https://cloud.githubusercontent.com/assets/13894380/23865871/abebe330-07dc-11e7-99e0-c251cd13c3f0.png)

**Color-Blind Scheme Disabled**
![image](https://cloud.githubusercontent.com/assets/13894380/23865962/f89b9fea-07dc-11e7-9f70-d0f0f6129c7c.png)

**Comment by arouinfar** [comment]
Good questions @Denz1994! I don't believe there's a codified rule for when to use colorblind red. Generally, we use it to improve contrast against a black background (e.g. oxygen atoms in Atomic Interactions). I don't particularly like using colorblind red unless necessary.

Using the colorblind preview modes of Illustrator, standard red doesn't appear to have contrast issues, so I'd recommend we stick to RGB red, rather than colorblind.
![image](https://cloud.githubusercontent.com/assets/8419308/23919005/b445c9fe-08ba-11e7-9dfe-230855eed8e6.png)  ![image](https://cloud.githubusercontent.com/assets/8419308/23919012/bda13ae2-08ba-11e7-8a2c-dd4e4571d9d8.png)

**Comment by Denz1994** [comment]
Okay, thanks for the input. I will follow your suggestion.

**Comment by Denz1994** [comment]
Commit 8f2e3cb50889006adca48214fcc82032f4e76a47 fixed this issue. Closing.
